### ISSUE TITLE
ValueError: View function did not return a response

### ISSUE THREAD

**Issue by UCRajkumar** [fu-malaria/fu-malaria#1]
Hello, 

I downloaded the software and I tried to upload a new image. The image is 300x300 and *.jpg. When I upload the image, I get the following error: 

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response`

I am not sure how to resolve this error. Could it possibly be an error with the image?

**Comment by topia47** [comment]
Hi @UCRajkumar , I've added a temporary fix to "_app.py_". It should work as intended now. I will continue to look for a more robust solution in the mean time. Thanks for bringing this to our attention :smile:

**Comment by topia47** [comment]
Feel free to open it up again, if the problem persists.

**Comment by UCRajkumar** [comment]
I'm a bit curious - what is the point of calc_sloop_change()? I can understand the code, but is there a particular algorithm/thresholding that it is mimicking?

**Comment by mikenicholls88** [comment]
Not sure, guy who wrote the original is now off working for the Linux foundation and has gone back to his home country, feel free to modify if you feel it can be improved
